server:
  port: 8080
  tomcat:
    threads:
      max: 10000
    max-connections: 10000

mybatis:
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: YGYin0307

  redis:
    host: localhost
    port: 6389
    database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest





